// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        kotlin_version = '2.2.0'
    }
    repositories {
        google()
        mavenCentral()

    }
/*
        // Do not use mavenCentral()
        maven {
            url 'https://repo1.maven.org/maven2'
        }*/

        // Do not use google()
      /*  maven {
            url 'https://maven.google.com'
        }*/

   /* maven {
        url 'https://s01.oss.sonatype.org/content/repositories/snapshots/'
    }
    maven {
        url 'https://jitpack.io'
    }*/
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
       // classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.0"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}

ext {
    packageName = "com.happy.pro"
    ndkVersion = "27.1.12297006"
    versionCode = 100
    versionName = "3.0.0"
}
