pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
    plugins {
        id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
        // id 'com.google.firebase.crashlytics' version '3.0.3'
    }
}
allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' } // Add this line
    }
}

rootProject.name = "COSMIC-M1"
include(":app")
